spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/footstep
    username:  sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  redis:
    port: 6379
    host: localhost
  mvc:
    path match:
      matching-strategy: ant_path_matcher
logging.level:
  org.hibernate.SQL: debug


